branch-defaults:
  master:
    environment: Eastoon
global:
  application_name: Eastoon-web
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
